apiVersion: v1
kind: ConfigMap
metadata:
  name: order-url
data:
  ORDER_SERVICE_URL: 'http://order.default.svc:8080'
  USER_SERVICE_URL: 'http://user.default.svc:8080'
  CART_SERVICE_URL: 'http://cart.default.svc:8080'
  RATING_SERVICE_URL: 'http://rating.default.svc:8080'
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-db
data:
  MYSQL_ID: 'root'
  MYSQL_ROOT_PASSWORD: 'root' ## TODO secret으로 빼기 
  MYSQL_DB: 'order'
  MYSQL_HOST: 'order-db.default.svc'
